### ISSUE TITLE
validate stock before insert/update

### ISSUE THREAD

**Issue by sensasi-delight** [sensasi-apps/sensasi-logistic#18]
- material in details
  - create: no validation
  - update:
    - new in material: no validation
    - [x] update material: is stock enough
    - [x] delete material: is detail used on out
- material out details:
  - [ ] create: is in details stock enough
  - [ ] update: is in details stock enough
- product in details:
  - create: no validation
  - update:
    - new in product: no validation
    - [ ] update product: is stock enough
    - [ ] delete product: is detail used on out
- product out details:
  - [ ] create: is in details stock enough
  - [ ] update: is in details stock enough 
- manufacture:
  - [ ] just like material out details and product in details

**Comment by MuhammadIrfanAnwari** [comment]
validasi di php bukan di mysql
